apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      serviceAccountName: banking-api-sa
#---------------------------------------------------------
## Init Container
      initContainers:
      - name: wait-for-db
        command:
        - sh
        - -c
        - |
          echo "Waiting for postgres-db:5432..."
          until nc -z postgres-db 5432; do
            echo "DB not ready, retrying in 2s..."
            sleep 2
          done
          echo "DB is ready!"
        image: busybox:1.36
#---------------------------------------------------------  
## Container
      containers:
      - image: ezzeldinabdulhafiz/banking-api:v1.0
        imagePullPolicy: Always
        name: banking-api
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
#---------------------------------------------------------  
## Probes
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 5

        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15

        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
#---------------------------------------------------------
## environment variables
        envFrom:
          - configMapRef:
              name: banking-config
          - secretRef:
              name: banking-secret
#---------------------------------------------------------
## Security
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
#---------------------------------------------------------
## pods placement affinity && toleration
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - high-memory
        # ── make sure that every pod runs on a differant node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - banking-api
            topologyKey: kubernetes.io/hostname

      tolerations:
      - effect: NoSchedule
        key: database-only
        operator: Equal
        value: "true"
#---------------------------------------------------------
## volumes
      volumes:
      - name: tmp
#---------------------------------------------------------
